### ISSUE TITLE
Not compatible with rails 6.1

### ISSUE THREAD

**Issue by jonian** [marcinruszkiewicz/where_chain#18]
Hi @marcinruszkiewicz, thanks for this gem. I tried using this with rails 6.1 but it fails with method missing for `where_clause_factory`, used [here](https://github.com/marcinruszkiewicz/where_chain/blob/1a1cd58e81c1e33745205a39d06babd7b207ebec/lib/active_record/where_chain_extensions_rails5.rb#L49).

If you are not planning to support rails 6.1, you should add `< 6.1` for activerecord dependency.

I would like to help with this, but I tried and could not make it work. I will give it another try and if it works, I will make a PR.

**Comment by CodeMeister** [comment]
Another issue needing resolved:

- new 6.1 Rails app
- model with validation: `validates :email, presence: true, uniqueness: { case_sensitive: false }`

when updating a record from the console, the error is:
```
NoMethodError (undefined method `sanitize_forbidden_attributes' for #<ActiveRecord::QueryMethods::WhereChain:0x00007fe03d85ae10>)
```

Removing `{ case_sensitive: false }` allows the update to proceed.
