### ISSUE TITLE
Rails 6 support

### ISSUE THREAD

**Issue by marcinruszkiewicz** [marcinruszkiewicz/where_chain#4]
I haven't yet looked if there are a lot of changes needed from the Rails 5 version, I'm expecting some, but not that many it will be unmanageable. 

The code is still in the same place as in 5 and on a first glance looks pretty much the same, though it should still be obviously tested.

What needs to be done here:

- [ ] add 6.0 to Appraisals file
- [ ] make sure the dummy app that's used for rspec still works in 6.0 or make it work
- [ ] add 6.0 to the CI config
- [ ] finally, pass the tests on 6.0 both locally and on CI

**Comment by dodo121** [comment]
I'm having a look at it.
